// Code generated by 'go run ./gen'; DO NOT EDIT
package cmd

import (
	"fmt"
	"github.com/pkg/profile"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"time"

	"github.com/oscarteg/advent-of-code-2020/challenge/day1"
	"github.com/oscarteg/advent-of-code-2020/challenge/day2"
	"github.com/oscarteg/advent-of-code-2020/challenge/day3"
)
